spring:
  profiles:
    active: a

  datasource:
    url: jdbc:mysql://10.1.200.214:3306/db_person
    username: mysqluser1
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
